# Generated by Django 2.0 on 2018-03-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sentence', '0002_auto_20180301_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='author',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='reference',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
