# Generated by Django 3.0.6 on 2020-11-02 08:42

import SmartDjango.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sentence', '0003_auto_20180301_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentence',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='sentence',
            name='author',
            field=SmartDjango.models.fields.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='reference',
            field=SmartDjango.models.fields.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=SmartDjango.models.fields.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=SmartDjango.models.fields.CharField(max_length=10, unique=True),
        ),
    ]
