# Generated by Django 3.0.6 on 2020-11-02 09:05

import SmartDjango.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', SmartDjango.models.fields.CharField(max_length=1024)),
                ('agent_key', SmartDjango.models.fields.CharField(max_length=64, unique=True)),
                ('visit_times', SmartDjango.models.fields.IntegerField()),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
    ]
