# Generated by Django 3.0.6 on 2020-11-04 12:13

import SmartDjango.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='sentence_to_share',
            field=SmartDjango.models.fields.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='share_times',
            field=SmartDjango.models.fields.IntegerField(default=0),
        ),
    ]
