# Generated by Django 3.0.6 on 2020-11-04 12:15

import SmartDjango.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0002_auto_20201104_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='share_author',
            field=SmartDjango.models.fields.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='share_reference',
            field=SmartDjango.models.fields.CharField(blank=True, max_length=20, null=True),
        ),
    ]
