# Generated by Django 3.0.6 on 2020-11-02 08:42

import SmartDjango.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20180301_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='user',
            name='inviter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=SmartDjango.models.fields.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pwd_change_time',
            field=SmartDjango.models.fields.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=SmartDjango.models.fields.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=SmartDjango.models.fields.CharField(blank=True, default=None, max_length=32, null=True, unique=True, verbose_name='用户名'),
        ),
    ]
